In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()


In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

#### Logistic Regression

In [4]:
# We can use different classifiers
lr = LogisticRegression(max_iter=10000)
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9722222222222222

#### SVM

In [5]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9888888888888889

#### Random Forest

In [6]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9722222222222222

<h3 style='color:green'>KFold cross validation</h3>

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
# For example
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
# instead of writing all, creating a function

def get_Score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [10]:
get_Score(LogisticRegression(max_iter=10000), x_train, x_test, y_train, y_test)

0.9722222222222222

In [11]:
get_Score(SVC(), x_train, x_test, y_train, y_test)

0.9888888888888889

In [12]:
# StratifiedKFold is similar to KFold but it is little better inway that when seperating folds
# It'll divide each category in uniform way

from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [13]:
# creating different array
score_l = []
score_svm = []
score_rf = []

for train_index,test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    print(get_Score(LogisticRegression(max_iter=10000), x_train, x_test, y_train, y_test))
    print(get_Score(SVC(), x_train, x_test, y_train, y_test))
    print(get_Score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

0.9282136894824707
0.9666110183639399
0.9365609348914858
0.9415692821368948
0.9816360601001669
0.9549248747913188
0.9165275459098498
0.9549248747913188
0.9298831385642737


In [14]:
# instead of print appending with the score array
for train_index,test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    score_l.append(get_Score(LogisticRegression(max_iter=10000), x_train, x_test, y_train, y_test))
    score_svm.append(get_Score(SVC(), x_train, x_test, y_train, y_test))
    score_rf.append(get_Score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

In [15]:
score_l

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [16]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [17]:
score_rf

[0.9332220367278798, 0.9582637729549248, 0.9265442404006677]

<h3 style='color:green'>cross_val_score function</h3>

In [18]:
# Instead of typing and appending (see cell no 33)
# sklearn library has cross_val_score

from sklearn.model_selection import cross_val_score

In [19]:
cross_val_score(LogisticRegression(max_iter=10000), digits.data, digits.target)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [20]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [21]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93611111, 0.91111111, 0.95264624, 0.96100279, 0.93036212])

##### Parameter tunning using k fold cross validation

In [22]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8803600248292988

In [23]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9443482309124767

In [24]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9437926753569211

In [25]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9398882681564246

Here we used cross_val_score to fine tune our random forest classifier and figured that having around 20 trees in random forest gives best result. 