<h2 style="color:green" align="center"> Machine Learning With Python: Linear Regression Multiple Variables</h2>


### Predict the house price of

1. 3000sqft, 3 bedrooms, 40 years old
2. 2500sqft, 4 bedrooms, 5 years old

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")

In [3]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
# handling the NaN value
# Taking the median value of the bedrooms & replacing it with NaN value coz all values are nearer to eachother
df.bedrooms.median()

3.5

In [5]:
#Converting 3.5 to integer value
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [6]:
# filling NaN value with 3
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
x = df.iloc[:,0:3]
y = df.iloc[:,-1]

In [8]:
# Creating the linear regression object
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)       #fit is udes for training the model


LinearRegression()

In [9]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [10]:
reg.intercept_

383724.9999999998

#### Price of 3000sqft, 3 bedrooms, 40 years old is

In [11]:
reg.predict([[3000,3,40]])

array([444400.])

In [12]:
444400 
# Its less comapares to df, because of the age 

444400

#### Price of 2500sqft, 4 bedrooms, 5 years old

In [13]:
reg.predict([[2500, 4, 5]])

array([588625.])